default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development_instatalk

test:
  <<: *default
  database: test_instatalk

production:
  <<: *default
  database: db/production.postgresql
